### PR TITLE
COH-23: Add list of cohort members to Cohort Request Resource

### PR DESCRIPTION
**Pull request by Fatmali**
https://issues.openmrs.org/browse/COH-23

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Fatmali i have made the ticket ready for work. Can you take it through the JIRA workflow?https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by Fatmali** [comment]
done @dkayiwa

**Comment by dkayiwa** [comment]
@Fatmali what is the next version of this module that you are targeting to release?

**Comment by Fatmali** [comment]
2.1.1 @dkayiwa

**Comment by dkayiwa** [comment]
Can you update the JIRA tickets to show that as the fix version?

**Comment by Fatmali** [comment]
done

**Pull request merged**
