### PR TITLE
Re-work cohort DAO Layer

### PR DESCRIPTION
**Pull request by kipchubett**
The purpose of this PR is to:
- Simplify `DAO` to few classes: Remove redundant code & split [`HibernateCohortDao.class`](https://github.com/openmrs/openmrs-module-cohort/blob/master/api/src/main/java/org/openmrs/module/cohort/api/db/hibernate/HibernateCohortDAO.java) into smaller, manageable, precise classes with specific 
- Favor criteria API
- Fix some query bugs
- Improve performance: - reduce database requests

### CODE REVIEW

**Review by ibacher — COMMENTED** [review]
These mostly look like changes for the best. However, I think it's better to retain the `Context.getService()` pattern where it exists. The reason is that this ensures that we always get the correct object graph.

In OpenMRS, every time a new module is loaded or a module is removed, the Spring context is refreshed, meaning the bean definitions are reloaded, but any previous Spring beans held in local variables aren't automatically updated. This leads to situations where the object graph behind a particular object is linked to a transactional context that no longer exists. Basically,  I worked around this in the FHIR2 module with [this hack](https://github.com/openmrs/openmrs-module-fhir2/commit/4289a6696c00ac81ab0a2fe78599e04df1ed093b#diff-39278913b9eade7e45de92df5d439350a0a087ee15b4af801bb1c8f44a74d2e4) which works on the assumption that everything is wired through FHIR providers.

Using `Context.getService()`, even where it seems redundant, is a defense against those kinds of issues.

Good work!

**Comment by dkayiwa** [comment]
> but any previous Spring beans held in local variables aren't automatically updated

I assume that the local variables were in non spring beans. Correct?

**Comment by ibacher** [comment]
> were in non spring beans

Eventually, yes, the root objects were held in a servlet which isn't managed by Spring.

**Comment by kipchubett** [comment]
> Using `Context.getService()`, even where it seems redundant, is a defense against those kinds of issues.

From [this method](https://github.com/openmrs/openmrs-core/blob/f76ee93cc46271997e577ed7fa223ac4a4e53dcb/api/src/main/java/org/openmrs/api/context/ServiceContext.java#L739), so long as the module service is implementing `OpenmrsService` interface. It will be re-added on refresh context

Probably, I should set explicitly to the ServiceContext i.e
```java
ServiceContext.getInstance().setService(CohortTypeService.class, new CohortTypeServiceImpl(dao));
```

**Comment by kipchubett** [comment]
After trying out the different approaches practically, I think I'm going to stick with `Context.getRegisteredComponent("cohort.cohortService", CohortService.class);` having register this beans using `@Component(value = "cohort.cohortService")` to the Spring context. The reason behind this is because it involves no additional code/less code & I dislike XML bean configuration. All the approaches work well.
```java
@Transactional
@Setter(AccessLevel.MODULE)
@Getter(AccessLevel.MODULE)
@Component(value = "cohort.cohortService")
public class CohortServiceImpl extends BaseOpenmrsService implements CohortService {
```
I think spring beans registered through servlet aren't re-add on refreshContext. Experience it once, dunno if it's consistent.

The alternative approach: accessible via `Context.getService(CohortService.class)` 
Maintaining the XML file [here](https://github.com/openmrs/openmrs-module-cohort/blob/master/api/src/main/resources/moduleApplicationContext.xml#L31)
OR
The equivalent Java code
```java
IGenericDao<CohortM> dao = new GenericDao<>();
dao.setWClazz(CohortM.class);
		
IGenericDao<CohortAttribute> attributeDao = new GenericDao<>();
attributeDao.setWClazz(CohortAttribute.class);
		
IGenericDao<CohortAttributeType> attributeTypeDao = new GenericDao<>();
attributeTypeDao.setWClazz(CohortAttributeType.class);
		
ServiceContext.getInstance().setService(CohortService.class,
	new CohortServiceImpl(dao, attributeDao, attributeTypeDao));
```
@ibacher @dkayiwa what are your thoughts on this?

**Comment by ibacher** [comment]
> I think spring beans registered through servlet aren't re-add on refreshContext.

Yeah, Spring can only override things in classes it manages. Servlets, filters, etc. are managed by the Servlet container rather than by Spring directly, so Spring can't really do too much.

I'm happy with ditching XML for configuration; however, we need to retain at least one of `moduleApplicationContext.xml` or `webModuleApplicationContext.xml`, even if they are effectively blank because of [this](https://github.com/openmrs/openmrs-core/blob/0548d24533824c66377884001c2807b3dff45ea5/web/src/main/java/org/openmrs/module/web/WebModuleUtil.java#L192).

**Comment by kipchubett** [comment]
@ibacher Should we get this in?

**Comment by ibacher** [comment]
Done. Thanks @corneliouzbett!

**Pull request merged**
