### PR TITLE
COH-49: Prevent deleting cohort Types when there are associated cohorts

### PR DESCRIPTION
**Pull request by ManojLL**
### Issue worked on: 
[COH-49](https://issues.openmrs.org/browse/COH-49?jql=project%20%3D%20COH)

### Description

This PR fixed the [issue](https://issues.openmrs.org/browse/COH-49?jql=project%20%3D%20COH) on purge cohort type when they are linked with cohorts.

### CODE REVIEW

**Comment by ManojLL** [comment]
@ibacher @dkayiwa , could you please review this PR?

**Comment by dkayiwa** [comment]
@ManojLL isn't it better to just put foreign key constraint restrictions at the database level? Just like we do for the rest of the openmrs core domain objects?

**Comment by ManojLL** [comment]
@dkayiwa if we add foreign key constraint restrictions at the database level, we can not purge cohort Type when it associate with voided (voided = true) cohort.

**Comment by dkayiwa** [comment]
> 

That would be a good thing because it would force us to first explicitly purge the voided cohort.

**Comment by ManojLL** [comment]
@dkayiwa okay, So shall I close this PR ?

**Comment by dkayiwa** [comment]
> 

Or you could replace it with liquibase changesets that add the database table foreign keys.

**Pull request closed without merging**
