### PR TITLE
Bump up the versions since 3.0.1 has been released at commit #b156e9f3265d585484b5b5fde16da85a28a75bb6

### PR DESCRIPTION
**Pull request by ssmusoke**

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ssmusoke i have actually thought that you were going to release 2.x something.

**Comment by ssmusoke** [comment]
@dkayiwa it was based off the 3.0.0-SNAPSHOT so is not on the 2.x line

**Comment by ibacher** [comment]
Well, the cut-off point for 3 was supposed to be this commit: 97f50e977a9f66bc1576a8901978891f0d8b770b, which is where we started removing functionality. However, if @ssmusoke module versions beyond that breaks for you, we should be releasing that as a major version and not 3.0.2 (per semver), so I kind of prefer that we release b156e9f3265d585484b5b5fde16da85a28a75bb6 as 2.1.0.

I.e., basically I thought we had some small improvements to the 2.x line but then from that point on things are intended to be breaking changes.

**Comment by ssmusoke** [comment]
@ibacher Noted, let me release a 2.1.0 

@dkayiwa Please can you help me delete the 3.0.1 from JFrog

**Comment by ibacher** [comment]
@ssmusoke It's been deleted.

**Comment by ssmusoke** [comment]
Thanks

**Pull request closed without merging**
