### PR TITLE
COH-22: Link Cohort Visits to Member Visits

### PR DESCRIPTION
**Pull request by Fatmali**
@dkayiwa

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Fatmali can you claim the ticket and take it through the JIRA workflow as outlined here? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

Remember to also include a link to the ticket, on this pull request, as advised in the above wiki page

**Comment by Fatmali** [comment]
@dkayiwa, I mistakenly set the status of this ticket to post commit review, can you assist and set it back to request code review? thanks.

**Comment by Fatmali** [comment]
Let me rebase and push

**Comment by Fatmali** [comment]
https://issues.openmrs.org/browse/COH-22

**Comment by dkayiwa** [comment]
@Fatmali can you look into these merge conflicts?
Is there a reason why you are not doing these pull requests against the master branch?

**Comment by Fatmali** [comment]
Hi @dkayiwa, there were some changes introduced into the 2.1.0 branch by @maimoonak and I to have this module run in OpenMRS version 2.1.x as it was previously not running. Those changes are yet to be merged into master, so all these changes I made are ontop of 2.1.0

**Comment by dkayiwa** [comment]
@Fatmali can't those changes be brought into the master branch?

**Comment by Fatmali** [comment]
@dkayiwa they can be merged. Can we first merge the remaining PR's into 2.1.0 then I will rebase 2.1.0 against master and create a PR against master? or how would you suggest we go about it?

**Comment by Fatmali** [comment]
or I merge 2.1.0 and master locally and force push upstream master? lol :-D

**Comment by dkayiwa** [comment]
Whichever you find easier, as long as you do not end up with features which are in the 2.1.0 branch but not in master

**Comment by Fatmali** [comment]
cool

**Pull request merged**
